srcimg:
  url: http://localhost:7000/image/current # will be overrided by process.env.SRCIMG_URL
mqtt:
  host: localhost  # will be overrided by process.env.MQTT_HOST
  port: 1883 # will be process.env.MQTT_PORT
  topic: motiondetection # will be process.env.MQTT_TOPIC
polling:
  interval: 250 # will be .... process.env.POLLING_INTERVAL
profile_url: http://localhost:7050/profile
